version: "3.9"

services:
  weather:
    image: ulexxander/weather-prometheus-exporters
    volumes:
      - "./config.json:/weather-prometheus-exporters/config.json"
    env_file: .env

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
